// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDexHNihTcuAIxPPWHQNCBWdz1KBszyPAw',
    appId: '1:167564632543:web:19598341a82d71e425246a',
    messagingSenderId: '167564632543',
    projectId: 'flutter-sns-udemy',
    authDomain: 'flutter-sns-udemy.firebaseapp.com',
    storageBucket: 'flutter-sns-udemy.appspot.com',
    measurementId: 'G-52B3N4RJJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMiBUYC2mpQcCXEMS2XL_eRVACds8J3eo',
    appId: '1:167564632543:android:cb3c7f5db9dae11025246a',
    messagingSenderId: '167564632543',
    projectId: 'flutter-sns-udemy',
    storageBucket: 'flutter-sns-udemy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsLJXW9E3D6pEh4Xtgl8xe5fYk_Wnrejw',
    appId: '1:167564632543:ios:f490c1f3ed117e6325246a',
    messagingSenderId: '167564632543',
    projectId: 'flutter-sns-udemy',
    storageBucket: 'flutter-sns-udemy.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
